"""
This type stub file was generated by pyright.
"""

import typing
from .url import Url
from ..connection import ProxyConfig

if typing.TYPE_CHECKING:
    ...
def connection_requires_http_tunnel(proxy_url: Url | None = ..., proxy_config: ProxyConfig | None = ..., destination_scheme: str | None = ...) -> bool:
    """
    Returns True if the connection requires an HTTP CONNECT through the proxy.

    :param URL proxy_url:
        URL of the proxy.
    :param ProxyConfig proxy_config:
        Proxy configuration from poolmanager.py
    :param str destination_scheme:
        The scheme of the destination. (i.e https, http, etc)
    """
    ...

